create database base_oi

    use base_oi;

    create table inventario_oi (
        id_circuito int(20) primary key auto_increment,
        numero_Logico varchar(20),
        chave_ddd varchar(20),
        chave_caixa varchar(20),
        contrato_caixa varchar(20),
        contrato varchar(15),
        valor_contrato int (20),
        observacao varchar(255),
        motivos_isentos_ varchar(30),
        acesso_associado varchar(20),
        oficio_solicitacao varchar(20),
        Data_Homologacao date,
        circuito_base_cliente varchar(20),
        numero_atividade varchar(20),
        uf varchar(2),
        local_local varchar(20),
        meio_terminal varchar(20),
        dt_instalacao date,
        ddd_codigo_regiao varchar(20),
        produto_dados_tipo_circuito varchar(30),
        velocidade varchar(20),
        cnpj_titular varchar(20),
        data_retirada date,
        local_Num varchar(20),
        cj_nao_tem_na_RII varchar(20),
        r_social_titular_titular varchar(20),
        su_nao_tem_na_rii varchar(20),
        ativo_inativo varchar(20),
        descricao_produto_sisraf varchar(255),
        ae varchar(20),
        ponta_a varchar(20),
        ponta_b varchar(20),
        ciclo varchar(20),
        dia_vencim date,
        aglutinador varchar(20),
        chavecpct varchar(20),
        ccus varchar(20),
        designacao_dados varchar(20),
        degrau_tarif_degrau varchar(20),
        tp_ccus varchar(20),
        cnpj_usuario varchar(20),
        categoria varchar(20),
        situacao varchar(20),
        contrato_2 varchar(20),
        agrupador varchar(20),
        servicos varchar(20),
        ciclo_2 varchar(20),
        terminal_anterior_ficticio varchar(20)

    );