create database base_oi

use base_oi;
create table inventario_oi (
        id_circuito int(20) primary key auto_increment,
        circuito varchar(20),
        velocidade varchar(20), 
        valor_contrato int (20),
        numero_logico varchar(20),
        chave_ddd varchar(20),
        chave_caixa varchar(20),
        contrato_caixa varchar(20),
        contrato_oi varchar(15),    
        observacao varchar(255),
        motivos_isentos_ varchar(30),
        acesso_associado varchar(20),
        oficio_solicitacao varchar(20),
        data_homologacao date,
        circuito_base_cliente varchar(20),
        numero_atividade varchar(20),
        cgc_filial varchar(20),
        gerenciado varchar(20),
        regiao varchar(20),
        site varchar(20),
        uf varchar(2),
        ciclo varchar(20),
        local_lit_local varchar(20),
        dia_vencimento date,  
        dt_instalacao date,
        chavecpct varchar(20),
        ddd_codigo_regiao varchar(20),
        ccus varchar(20),
        produto_dados_tipo_circuito varchar(30),
        designacao_dados varchar(20),
        degrau_tarif_degrau varchar(20),
        cnpj_titular varchar(20),
        tp_ccus varchar(20),
        data_retirada date,
        cnpj_usuario varchar(20),
        local_Num varchar(20),
        categoria varchar(20),
        cj_nao_tem_na_RII varchar(20),
        situacao varchar(20),
        r_social_titular_titular varchar(20),
        contrato varchar(20),
        su_nao_tem_na_rii varchar(20),
        ativo_inativo varchar(20),
        servicos varchar(20), 
        descricao_produto_sisraf varchar(255),
        aglutinador varchar(20),
        agrupador varchar(20), 
        meio_terminal varchar(20),
        ciclo_2 varchar(20),
        ae varchar(20),
        terminal_anterior_ficticio varchar(20),
        ponta_a varchar(20),
        ponta_b varchar(20)
     
    );